/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app/settings'
import { Route as AuthenticatedAppScanRouteImport } from './routes/_authenticated/app/scan'
import { Route as AuthenticatedAppRemediationRouteImport } from './routes/_authenticated/app/remediation'
import { Route as AuthenticatedAppPrioritizationRouteImport } from './routes/_authenticated/app/prioritization'
import { Route as AuthenticatedAppFindingsRouteImport } from './routes/_authenticated/app/findings'
import { Route as AuthenticatedAppComplianceRouteImport } from './routes/_authenticated/app/compliance'
import { Route as AuthenticatedAppAssetsRouteImport } from './routes/_authenticated/app/assets'
import { Route as AuthenticatedAppAssetsAssetIdRouteImport } from './routes/_authenticated/app/assets.$assetId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppScanRoute = AuthenticatedAppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppRemediationRoute =
  AuthenticatedAppRemediationRouteImport.update({
    id: '/remediation',
    path: '/remediation',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPrioritizationRoute =
  AuthenticatedAppPrioritizationRouteImport.update({
    id: '/prioritization',
    path: '/prioritization',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppFindingsRoute =
  AuthenticatedAppFindingsRouteImport.update({
    id: '/findings',
    path: '/findings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppComplianceRoute =
  AuthenticatedAppComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAssetsRoute = AuthenticatedAppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppAssetsAssetIdRoute =
  AuthenticatedAppAssetsAssetIdRouteImport.update({
    id: '/$assetId',
    path: '/$assetId',
    getParentRoute: () => AuthenticatedAppAssetsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/app/assets': typeof AuthenticatedAppAssetsRouteWithChildren
  '/app/compliance': typeof AuthenticatedAppComplianceRoute
  '/app/findings': typeof AuthenticatedAppFindingsRoute
  '/app/prioritization': typeof AuthenticatedAppPrioritizationRoute
  '/app/remediation': typeof AuthenticatedAppRemediationRoute
  '/app/scan': typeof AuthenticatedAppScanRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/assets/$assetId': typeof AuthenticatedAppAssetsAssetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/assets': typeof AuthenticatedAppAssetsRouteWithChildren
  '/app/compliance': typeof AuthenticatedAppComplianceRoute
  '/app/findings': typeof AuthenticatedAppFindingsRoute
  '/app/prioritization': typeof AuthenticatedAppPrioritizationRoute
  '/app/remediation': typeof AuthenticatedAppRemediationRoute
  '/app/scan': typeof AuthenticatedAppScanRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/assets/$assetId': typeof AuthenticatedAppAssetsAssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/app/assets': typeof AuthenticatedAppAssetsRouteWithChildren
  '/_authenticated/app/compliance': typeof AuthenticatedAppComplianceRoute
  '/_authenticated/app/findings': typeof AuthenticatedAppFindingsRoute
  '/_authenticated/app/prioritization': typeof AuthenticatedAppPrioritizationRoute
  '/_authenticated/app/remediation': typeof AuthenticatedAppRemediationRoute
  '/_authenticated/app/scan': typeof AuthenticatedAppScanRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/assets/$assetId': typeof AuthenticatedAppAssetsAssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app'
    | '/app/assets'
    | '/app/compliance'
    | '/app/findings'
    | '/app/prioritization'
    | '/app/remediation'
    | '/app/scan'
    | '/app/settings'
    | '/app/'
    | '/app/assets/$assetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/assets'
    | '/app/compliance'
    | '/app/findings'
    | '/app/prioritization'
    | '/app/remediation'
    | '/app/scan'
    | '/app/settings'
    | '/app'
    | '/app/assets/$assetId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/_authenticated/app'
    | '/_authenticated/app/assets'
    | '/_authenticated/app/compliance'
    | '/_authenticated/app/findings'
    | '/_authenticated/app/prioritization'
    | '/_authenticated/app/remediation'
    | '/_authenticated/app/scan'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/'
    | '/_authenticated/app/assets/$assetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/scan': {
      id: '/_authenticated/app/scan'
      path: '/scan'
      fullPath: '/app/scan'
      preLoaderRoute: typeof AuthenticatedAppScanRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/remediation': {
      id: '/_authenticated/app/remediation'
      path: '/remediation'
      fullPath: '/app/remediation'
      preLoaderRoute: typeof AuthenticatedAppRemediationRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/prioritization': {
      id: '/_authenticated/app/prioritization'
      path: '/prioritization'
      fullPath: '/app/prioritization'
      preLoaderRoute: typeof AuthenticatedAppPrioritizationRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/findings': {
      id: '/_authenticated/app/findings'
      path: '/findings'
      fullPath: '/app/findings'
      preLoaderRoute: typeof AuthenticatedAppFindingsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/compliance': {
      id: '/_authenticated/app/compliance'
      path: '/compliance'
      fullPath: '/app/compliance'
      preLoaderRoute: typeof AuthenticatedAppComplianceRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/assets': {
      id: '/_authenticated/app/assets'
      path: '/assets'
      fullPath: '/app/assets'
      preLoaderRoute: typeof AuthenticatedAppAssetsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/assets/$assetId': {
      id: '/_authenticated/app/assets/$assetId'
      path: '/$assetId'
      fullPath: '/app/assets/$assetId'
      preLoaderRoute: typeof AuthenticatedAppAssetsAssetIdRouteImport
      parentRoute: typeof AuthenticatedAppAssetsRoute
    }
  }
}

interface AuthenticatedAppAssetsRouteChildren {
  AuthenticatedAppAssetsAssetIdRoute: typeof AuthenticatedAppAssetsAssetIdRoute
}

const AuthenticatedAppAssetsRouteChildren: AuthenticatedAppAssetsRouteChildren =
  {
    AuthenticatedAppAssetsAssetIdRoute: AuthenticatedAppAssetsAssetIdRoute,
  }

const AuthenticatedAppAssetsRouteWithChildren =
  AuthenticatedAppAssetsRoute._addFileChildren(
    AuthenticatedAppAssetsRouteChildren,
  )

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppAssetsRoute: typeof AuthenticatedAppAssetsRouteWithChildren
  AuthenticatedAppComplianceRoute: typeof AuthenticatedAppComplianceRoute
  AuthenticatedAppFindingsRoute: typeof AuthenticatedAppFindingsRoute
  AuthenticatedAppPrioritizationRoute: typeof AuthenticatedAppPrioritizationRoute
  AuthenticatedAppRemediationRoute: typeof AuthenticatedAppRemediationRoute
  AuthenticatedAppScanRoute: typeof AuthenticatedAppScanRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppAssetsRoute: AuthenticatedAppAssetsRouteWithChildren,
  AuthenticatedAppComplianceRoute: AuthenticatedAppComplianceRoute,
  AuthenticatedAppFindingsRoute: AuthenticatedAppFindingsRoute,
  AuthenticatedAppPrioritizationRoute: AuthenticatedAppPrioritizationRoute,
  AuthenticatedAppRemediationRoute: AuthenticatedAppRemediationRoute,
  AuthenticatedAppScanRoute: AuthenticatedAppScanRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
